### ISSUE TITLE
Blueprint Support

### ISSUE THREAD

**Issue by lleyton** [tau-OS/vala-template#2]
### Problem

UI files are pretty inconvenient for developers to use.

### Proposal

Support Blueprint.

**Comment by lainsce** [comment]
Before we decide on things we should actually think about writing the developer tutorials and stuff and then decide; Blueprint or UI?

**Comment by lleyton** [comment]
Fair enough, our DX is currently lacking

**Comment by lexisother** [comment]
This should have been closed with f423cb57ce116a9cbcd3db09291a21d89f9dae5e.
